//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public long id { get; set; }
        public string vendor { get; set; }
        public string model { get; set; }
        public short year { get; set; }
        public string modification { get; set; }
        public string nut { get; set; }
        public bool is_bolt { get; set; }
        public string pcd { get; set; }
        public string dia { get; set; }
        public string data { get; set; }
    }
}
