//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class operation
    {
        public long OperationId { get; set; }
        public string OperationType { get; set; }
        public Nullable<long> SaleNumber { get; set; }
        public System.DateTime OperationDate { get; set; }
        public System.DateTime OperationTime { get; set; }
        public int Count { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Storehouse { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public decimal Price { get; set; }
        public string PayType { get; set; }
        public string CardPay { get; set; }
        public Nullable<int> CardCheck { get; set; }
        public int CardToTotalSum { get; set; }
        public string Comment { get; set; }
        public int UserId { get; set; }
    }
}
