//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ProductId { get; set; }
        public string ProdNumber { get; set; }
        public bool ProdStatus { get; set; }
        public int CategoryId { get; set; }
        public int Width { get; set; }
        public float Height { get; set; }
        public string Radius { get; set; }
        public string Country { get; set; }
        public int ManufacturerId { get; set; }
        public int ModelId { get; set; }
        public string Articul { get; set; }
        public string Season { get; set; }
        public string InCol { get; set; }
        public string IsCol { get; set; }
        public string Gruz { get; set; }
        public string RFT { get; set; }
        public string Spikes { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> OptPrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
    }
}
