//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesreceipt
    {
        public long Id { get; set; }
        public System.DateTime Datetime { get; set; }
        public decimal Price { get; set; }
        public int StorehouseId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
    }
}
