//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_setting
    {
        public int setting_id { get; set; }
        public int store_id { get; set; }
        public string code { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public bool serialized { get; set; }
    }
}
