//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_affiliate_activity
    {
        public int activity_id { get; set; }
        public int affiliate_id { get; set; }
        public string key { get; set; }
        public string data { get; set; }
        public string ip { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
