//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_mws_return
    {
        public int id { get; set; }
        public string invoice_id { get; set; }
        public string amount { get; set; }
        public int status { get; set; }
        public string techMessage { get; set; }
        public int error { get; set; }
        public string cause { get; set; }
        public string clientOrderId { get; set; }
        public System.DateTime date { get; set; }
        public string response { get; set; }
        public string request { get; set; }
    }
}
