//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_disks
    {
        public int n { get; set; }
        public int gnum { get; set; }
        public string mfc { get; set; }
        public string model { get; set; }
        public string name { get; set; }
        public string color { get; set; }
        public string width { get; set; }
        public int diameter { get; set; }
        public int holes { get; set; }
        public float pcd { get; set; }
        public int et { get; set; }
        public string dia { get; set; }
        public string weight { get; set; }
        public string volume { get; set; }
        public int rquantity { get; set; }
        public int price { get; set; }
        public string img { get; set; }
        public string comment { get; set; }
    }
}
