//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_product_option_value
    {
        public int product_option_value_id { get; set; }
        public int product_option_id { get; set; }
        public int product_id { get; set; }
        public int option_id { get; set; }
        public int option_value_id { get; set; }
        public int quantity { get; set; }
        public bool subtract { get; set; }
        public decimal price { get; set; }
        public string price_prefix { get; set; }
        public int points { get; set; }
        public string points_prefix { get; set; }
        public decimal weight { get; set; }
        public string weight_prefix { get; set; }
    }
}
