//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_marketing
    {
        public int marketing_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public int clicks { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
