//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_return_history
    {
        public int return_history_id { get; set; }
        public int return_id { get; set; }
        public int return_status_id { get; set; }
        public bool notify { get; set; }
        public string comment { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
