//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_coupon
    {
        public int coupon_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public decimal discount { get; set; }
        public bool logged { get; set; }
        public bool shipping { get; set; }
        public decimal total { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
        public int uses_total { get; set; }
        public string uses_customer { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
