//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_order_total
    {
        public int order_total_id { get; set; }
        public int order_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public decimal value { get; set; }
        public int sort_order { get; set; }
    }
}
