//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_affiliate
    {
        public int affiliate_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string company { get; set; }
        public string website { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public int country_id { get; set; }
        public int zone_id { get; set; }
        public string code { get; set; }
        public decimal commission { get; set; }
        public string tax { get; set; }
        public string payment { get; set; }
        public string cheque { get; set; }
        public string paypal { get; set; }
        public string bank_name { get; set; }
        public string bank_branch_number { get; set; }
        public string bank_swift_code { get; set; }
        public string bank_account_name { get; set; }
        public string bank_account_number { get; set; }
        public string ip { get; set; }
        public bool status { get; set; }
        public bool approved { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
