//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_pokupki_orders
    {
        public int id_order { get; set; }
        public string id_market_order { get; set; }
        public string currency { get; set; }
        public string ptype { get; set; }
        public string home { get; set; }
        public string pmethod { get; set; }
        public string outlet { get; set; }
    }
}
