//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_coupon_history
    {
        public int coupon_history_id { get; set; }
        public int coupon_id { get; set; }
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
