//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_gift_teaser
    {
        public int gift_id { get; set; }
        public int item_id { get; set; }
        public Nullable<int> start_date { get; set; }
        public Nullable<int> end_date { get; set; }
        public int store_id { get; set; }
        public int condition_type { get; set; }
        public string condition_properties { get; set; }
        public string description { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
