//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_comdb_summer
    {
        public int product_id { get; set; }
        public string tag { get; set; }
        public string manufacturer_id { get; set; }
        public string model { get; set; }
        public string text_12 { get; set; }
        public string text_13 { get; set; }
        public string text_14 { get; set; }
        public string text_16 { get; set; }
        public string text_17 { get; set; }
        public string text_18 { get; set; }
        public string text_19 { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    }
}
