//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_voucher
    {
        public int voucher_id { get; set; }
        public int order_id { get; set; }
        public string code { get; set; }
        public string from_name { get; set; }
        public string from_email { get; set; }
        public string to_name { get; set; }
        public string to_email { get; set; }
        public int voucher_theme_id { get; set; }
        public string message { get; set; }
        public decimal amount { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
