//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tsrim
    {
        public int n { get; set; }
        public string oid { get; set; }
        public string sku { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string width { get; set; }
        public string diameter { get; set; }
        public string bcounts { get; set; }
        public string pcd { get; set; }
        public string et { get; set; }
        public string dia { get; set; }
        public string color { get; set; }
        public string img { get; set; }
        public string price { get; set; }
        public int amount { get; set; }
    }
}
