//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tyreshop.DbAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u0324292_tyreshopEntities : DbContext
    {
        public u0324292_tyreshopEntities()
            : base("name=u0324292_tyreshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<manufacturer> manufacturers { get; set; }
        public virtual DbSet<model> models { get; set; }
        public virtual DbSet<operation> operations { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<productquantity> productquantities { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<salesreceipt> salesreceipts { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<storehouse> storehouses { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
